# Generated by Django 6.0.2 on 2026-06-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_happycustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='Fan favourites', help_text='Small text above main heading', max_length=100)),
                ('title', models.CharField(default='Customer-loved Chelu classic', help_text='Main heading of the slide', max_length=200)),
                ('image', models.ImageField(help_text='Saree photo or showcase image', upload_to='hero_slides/')),
                ('button_text', models.CharField(default='SHOP NOW', help_text='Call to action button text', max_length=50)),
                ('button_url', models.CharField(default='/shop/', help_text='URL / shop category URL to redirect to', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower is first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
