# Generated by Django 6.0.6 on 2026-06-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_heroslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoutiqueSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Chelu by Sini', max_length=200)),
                ('address', models.TextField(default="Sini's Design Studio, Bangalore, India")),
                ('phone', models.CharField(default='+91 98765 43210', max_length=50)),
                ('email', models.EmailField(default='support@chelubysini.com', max_length=254)),
                ('shipping_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('hours', models.CharField(default='Mon - Sat: 10:00 AM - 7:00 PM', max_length=200)),
            ],
        ),
    ]
