# Generated by Django 6.0.6 on 2026-06-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_boutiquesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutiquesettings',
            name='upi_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
    ]
