# Generated by Django 6.0.2 on 2026-06-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_boutiquesettings_upi_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutiquesettings',
            name='phone',
            field=models.CharField(default='+91 94973 60705', max_length=50),
        ),
    ]
